"""modelos iniciales

Revision ID: 6ecd64c69030
Revises: 
Create Date: 2026-09-05 16:33:04.605370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ecd64c69030'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('negocios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('greeting', sa.Text(), nullable=True),
    sa.Column('default_reply', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('autoresponder', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_negocios'))
    )
    op.create_index(op.f('ix_negocios_slug'), 'negocios', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('conversaciones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('negocio_id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], name=op.f('fk_conversaciones_negocio_id_negocios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversaciones'))
    )
    op.create_index(op.f('ix_conversaciones_negocio_id'), 'conversaciones', ['negocio_id'], unique=False)
    op.create_index(op.f('ix_conversaciones_token'), 'conversaciones', ['token'], unique=True)
    op.create_table('reglas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('negocio_id', sa.Uuid(), nullable=False),
    sa.Column('keyword', sa.String(length=200), nullable=False),
    sa.Column('respuesta', sa.Text(), nullable=False),
    sa.Column('posicion', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], name=op.f('fk_reglas_negocio_id_negocios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reglas')),
    sa.UniqueConstraint('negocio_id', 'posicion', name='uq_reglas_negocio_posicion')
    )
    op.create_index(op.f('ix_reglas_negocio_id'), 'reglas', ['negocio_id'], unique=False)
    op.create_table('mensajes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversacion_id', sa.Uuid(), nullable=False),
    sa.Column('autor', sa.String(length=10), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("autor IN ('visitor', 'bot')", name=op.f('ck_mensajes_autor_valido')),
    sa.ForeignKeyConstraint(['conversacion_id'], ['conversaciones.id'], name=op.f('fk_mensajes_conversacion_id_conversaciones'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mensajes'))
    )
    op.create_index(op.f('ix_mensajes_conversacion_id'), 'mensajes', ['conversacion_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mensajes_conversacion_id'), table_name='mensajes')
    op.drop_table('mensajes')
    op.drop_index(op.f('ix_reglas_negocio_id'), table_name='reglas')
    op.drop_table('reglas')
    op.drop_index(op.f('ix_conversaciones_token'), table_name='conversaciones')
    op.drop_index(op.f('ix_conversaciones_negocio_id'), table_name='conversaciones')
    op.drop_table('conversaciones')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_negocios_slug'), table_name='negocios')
    op.drop_table('negocios')
    # ### end Alembic commands ###
